name: juce_ipc
description: Implementation of inter-process communication classes from JUCE
version: 0.0.1
homepage: https://github.com/Barabas5532/flutter_juce_ipc

publish_to: 'none'

environment:
  sdk: '>=2.19.0-1 <3.0.0'

dependencies:
  collection: ^1.17.0
  freezed_annotation: ^2.2.0
  logging: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.0
  dart_pre_commit: ^4.0.0
  dcli_core: ^2.0.1
  freezed: ^2.0.0
  lints: ^2.0.1
  stdlibc: ^0.1.1
  test: ^1.0.0

# These are unlikely to cause issues, and are checked in CI anyway
dart_pre_commit:
  flutter-compat: false
  outdated: false
  pull-up-dependencies: false
